"""
Source Attribution & Citation Validation module for CLAUSE Enterprise RAG.

Parses, validates, and maps inline citations ([S1], [S2]) from generated LLM text
against actual retrieved context sources. Filters out fabricated source references.
"""

import re
from typing import List, Dict, Tuple, Set, Any
from src.models import SourceReference
from src.prompt_builder import REFUSAL_SENTENCE


def parse_and_validate_citations(
    llm_response_text: str,
    source_map: Dict[str, SourceReference],
) -> Tuple[List[SourceReference], bool, Dict[str, Any]]:
    """
    Parse inline citations (e.g., [S1], [S2]) from generated text, validate against source_map,
    and return structured SourceReference objects.

    Args:
        llm_response_text: Raw response string generated by Gemini.
        source_map: Mapping of source_id ("S1", "S2") -> SourceReference.

    Returns:
        Tuple of:
        - validated_sources (List[SourceReference]): List of valid cited SourceReference objects.
        - is_grounded (bool): True if cited sources match evidence or refusal; False if ungrounded claims made without valid citations.
        - attribution_diagnostics (Dict[str, Any]): Detailed citation parsing metrics.
    """
    is_refusal = (
        REFUSAL_SENTENCE.lower() in llm_response_text.lower()
        or "could not find sufficient information" in llm_response_text.lower()
    )

    # Find all source tags like [S1], [S2]
    raw_citations = re.findall(r"\[S(\d+)\]", llm_response_text)
    cited_ids = [f"S{c_num}" for c_num in raw_citations]

    seen_ids: Set[str] = set()
    valid_sources: List[SourceReference] = []
    invalid_ids: List[str] = []

    for sid in cited_ids:
        if sid in source_map:
            if sid not in seen_ids:
                seen_ids.add(sid)
                valid_sources.append(source_map[sid])
        else:
            invalid_ids.append(sid)

    # Sort validated sources by original retrieval rank
    valid_sources.sort(key=lambda s: s.retrieval_rank)

    # Groundedness determination:
    # 1. If it's an explicit refusal, it is grounded in refusal policy.
    # 2. If it's a claim with at least 1 valid citation, it is grounded.
    # 3. If it makes claims but has 0 valid citations, it is flagged as ungrounded (is_grounded = False).
    if is_refusal:
        is_grounded = True
    elif len(valid_sources) > 0:
        is_grounded = True
    else:
        # Factual claims without any valid inline source citations
        is_grounded = False

    diagnostics = {
        "is_refusal": is_refusal,
        "total_citations_found": len(cited_ids),
        "valid_citations_count": len(valid_sources),
        "invalid_citations_count": len(invalid_ids),
        "invalid_citations_list": invalid_ids,
        "is_grounded": is_grounded,
    }

    return valid_sources, is_grounded, diagnostics
